name: Theme Check

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/cla.yml'
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/cla.yml'

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # can be 3.0 or 2.7 also

      - name: Install theme-check
        run: |
          gem install theme-check

      - name: Run theme-check
        run: |
          theme-check
