name: CLA Check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run Shopify CLA Check
        uses: Shopify/shopify-cla-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-token: ${{ secrets.CLA_TOKEN }}
